GeoNet/fits

- plot.go
Document existing stddev func.
Pull out funcs to load obs and find min and max.
@bpeng - I think these functions should help simplify you're pull request a lot. 
Merge this one when you're happy with it.
> Observation functions

- plot.go
Should help with your observation statistics work.
> Add methodID to loadObs func.

- .gitignore
- Dockerfile
- docker.sh
- vendor/github.com/GeoNet/log/LICENSE
- vendor/github.com/GeoNet/log/logentries/logentries.go
- vendor/vendor.json
> Docker build

- build-push.sh
- build.sh
Add latest tag to images to make testing with docker-compose easier.
> Improve Docker build.

- fits-api/assets/api-docs/endpoint/plot
- fits-api/plot_site.go
- fits-api/plot_sites.go
- ts/plot.go
- ts/plot_templates.go
- ts/spark_templates.go
Resolved #94. We can add as many colour schemes as we want.
Resolved #95.
> Add the color scheme selector (e.g. better display for projector).

- fits-api/assets/api-docs/endpoint/plot
- fits-api/plot_site.go
- fits-api/plot_sites.go
> Plot now allows to use start parameter without specifying days.

- .travis.yml
Added the flag '--no-include-email' for Travis to work.
> Modified aws command syntax in travis

- cmd/fits-api/routes_test.go
- internal/valid/valid.go
- internal/valid/valid_test.go
- fix bug with parsing sites query parameter that should ignore any network code on the site code.
- None
> fix sites validation bug

- .travis.yml
- build.sh
Resolves #.
- Go version update
- Alpine version update
-
- None
> Go + Alpine Update

- .travis.yml
- cmd/fits-api/observation.go
- cmd/fits-api/plot_site.go
- cmd/fits-api/plot_sites.go
- cmd/fits-api/site_markers.go
- cmd/fits-api/spatialObservations.go
- internal/ts/plot.go
- internal/valid/valid.go
Resolves #.
- Applying lint.
-
-
- None
> Applying golangci-lint.

- vendor/github.com/GeoNet/kit/weft/handlers.go
- vendor/vendor.json
> missing header in weft

- dapper/dapperlib/types.go
- dapper/dapperlib/types_test.go
Resolves #164
- Change metrics data aggregation options
- None
> change data aggregation options

- dapper/dapperlib/types.go
> Fix aggregate bugs in dapper-api

- dapper/cmd/dapper-db-ingest/main.go
Resolves #. Add more logs for db-ingest for debugging
- 
-
-
- None
> Add more logs for db-ingest for debugging

- dapper/dapperlib/client.go
- Fix improper variable naming.
-
-
- None
> Improper variable naming.

- build-push.sh
- dapper/README.md
Resolves #.
- Added dapper's README
- Added build and push script for dapper images.
-
- None
> Update README. Add dapper's docker build script into deployment process.

- build-push.sh
Resolves  Dapper images not built in Travis.
- 
-
-
- None
> Fix docker image script.

- dapper/cmd/dapper-api/data.go
- Previously dapper-api will keep refreshing when requests arrived at the time metrics is collecting.
This PR gives the cache a minimum valid time window, during the window the cache doesn't refresh.
- dapper-api
> Add valid threshold for dapper-api all devices cache.

- dapper/README.md
- dapper/cmd/dapper-api/data.go
- dapper/cmd/dapper-api/env.list
- dapper/cmd/dapper-db-archive/env.list
- dapper/cmd/dapper-db-archive/main.go
- dapper/dapperlib/types.go
- Fix dapper-api data api's starttime/endtime/field parameter bug.  
- Enable dapper-db-archive to delete archived records from database.
-
- dapper-api
- dapper-db-archive
> Dapper cache fix

- dapper/dapperlib/testdata/aggrred.json
- dapper/dapperlib/testdata/source.json
- dapper/dapperlib/types.go
- dapper/dapperlib/types_test.go
> Fix aggregation bug.

- cmd/fits-api/assets/api-docs/endpoint/observation_stats.html
> DOCS Fix minor spelling mistakes

- .travis.yml
- README.md
- build-push.sh
- build.sh
- cmd/fits-api/routes_dev_test.go
- cmd/fits-api/site.go
- etc/Dockerfile
- etc/scripts/initdb-fits.sh
- go.mod
- go.sum
- vendor/github.com/GeoNet/kit/map180/bbox.go
- vendor/github.com/GeoNet/kit/metrics/ddog_http.go
- vendor/github.com/GeoNet/kit/metrics/ddog_msg.go
- vendor/github.com/GeoNet/kit/weft/assets.go
- vendor/github.com/GeoNet/kit/weft/errors.go
- vendor/github.com/GeoNet/kit/weft/handlers.go
- vendor/github.com/GeoNet/kit/weft/wefttest/wefttest.go
- vendor/modules.txt
- Change deprecated PostGIS function [`ST_Shift_Longitude`](https://postgis.net/docs/ST_Shift_Longitude.html) that is no longer available in `PostGIS-3` (new function works with `PostGIS-2.2` and above)
- Update Database docker to `PostgreSQL-12/PostGIS-3.0` (for test only, production database is installed using **AWS RDS**)
- Add routing tests against real database in `fits-api` 
- Depends on changes in [kit](https://github.com/GeoNet/kit/pull/76).
#GeoNet/tickets/issues/5779
- None
*Insert check list …
> Postgres update

- build-push.sh
Fix Docker build error: https://travis-ci.org/github/GeoNet/fits/builds/731146610
- None
> fix docker build error

- .travis.yml
Resolves #.
- update default branch to main
-
-
- None
> Update default main branch

- .travis.yml
- Dockerfile
- build.sh
- push.sh
> Add multistage docker build

- Dockerfile_template
- build.sh
Resolves #.
- switch to geonet base go-scratch image
-
-
- None
> switch back to geonet base image go-scratch

- etc/Dockerfile
Resolves #.
- update to geonet docker image
-
-
- None
> update to geonet base image

- cmd/fits-api/server.go
Enable CORS for fits-api as required in #206 
- None
> enable CORS for fits-api

- .travis.yml
- Dockerfile_template
- build.sh
- cmd/fits-api/server.go
- dapper/cmd/dapper-api/server.go
- dapper/dockerbuild.sh
- dapper/go.mod
- go.mod
Reference: https://github.com/GeoNet/tickets/issues/11752 , https://github.com/GeoNet/tickets/issues/11780
- Add timeout to server connections 
- Upgrade go version to `1.16`
- None
> Add timeout, upgrade go version to 1.16

- cmd/fits-api/assets/charts.html
Reference: https://github.com/GeoNet/tickets/issues/10754
**Changes**
- Remove unneeded form element to stop false positive security alert for CSRF
- None
**Code Review Guide**
- Tested ZAP scanner locally, alert no longer there.
- I tried creating test Database using the instructions in README.md, but got errors.
> Address CSRF warning

- dapper/etc/ddl/dapper-test-data.ddl
Existing test init script deletes all record which might no ideal when there're other live records.
- 
-
-
- None
> Fix domain error for dapper tests init script.

- .travis.yml
Adding slack notification stanza to .travis.yml file (https://github.com/GeoNet/tickets/issues/11986)
> add_slack_notifications_to_travis

- internal/valid/valid.go
Ticket https://github.com/GeoNet/tickets/issues/12924
- None
> fix type validation issue

- .github/workflows/build.yml
- cmd/fits-api/assets/api-docs/endpoint/observation.html
- cmd/fits-api/assets/api-docs/index.html
- cmd/fits-api/valid.go
Ticket https://github.com/GeoNet/tickets/issues/14172
- Add banner for FITS to Tilde migration in required pages
- None
> add tilde banner 

- dapper/cmd/dapper-api/data.go
> fix init bug

- cmd/fits-api/assets/api-docs/index.html
Ticket https://github.com/GeoNet/tickets/issues/17100
- Update banner for fits deprecate notice
- None
> Update banner for fits deprecate notice
